name: Esport ServeƦ

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Processing Esport ServeƦ
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Checking Esport ServeƦ Runners"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initialization Esport ServeƦ
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Main Repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} esport
       - name: Running Esport ServeƦ
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd esport
           docker build . -t esport
           docker run esport
       - name: Restarting Esport ServeƦ
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> Esport.txt
              git add Esport.txt
              git commit -m "Esport ServeƦ : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:EsportServeƦ
